### ISSUE TITLE
Google ProtoBuf ArgumentOutOfRangeException in built android app

### ISSUE THREAD

**Issue by geekoftheweek** [senseix/thinksy_unity_plugin#13]
Previewing my game in the Unity editor works fine.  Problems are retrieved, answers are submitted, etc.  However, when running the built application on my Nexus 5 (running Android 5.0 Lollipop), the Thinksy prefab never displays a question.  Examining the logcat shows the following:

    D/Unity   ( 4084): GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_sync GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_
    D/Unity   ( 4084): texture_sRGB_decode GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_render_to_texture GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_disjoint_timer_query
    I/Unity   ( 4084): ArgumentOutOfRangeException: Argument is out of range.
    I/Unity   ( 4084): Parameter name: options
    I/Unity   ( 4084):   at System.Text.RegularExpressions.Regex.validate_options (RegexOptions options) [0x00000] in <filename unknown>:0
    I/Unity   ( 4084):   at System.Text.RegularExpressions.Regex..ctor (System.String pattern, RegexOptions options) [0x00000] in <filename unknown>:0
    I/Unity   ( 4084):   at Google.ProtocolBuffers.Descriptors.DescriptorPool..cctor () [0x00000] in <filename unknown>:0
    I/Unity   ( 4084): Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Google.ProtocolBuffers.Descriptors.DescriptorPool

    I/Unity   ( 4084):   at Google.ProtocolBuffers.Descriptors.FileDescriptor.BuildFrom (Google.ProtocolBuffers.DescriptorProtos.FileDescriptorProto proto, Google.ProtocolBuffers.Descriptors.FileDescriptor[] dependencies) [0x00000] in <filename unknown>:0
    I/Unity   ( 4084):   at Google.ProtocolBuffers.Descriptors.FileDescriptor.InternalBuildGeneratedFileFrom (System.Byte[] descriptorData, Google.ProtocolBuffers.Descriptors.FileDescriptor[] dependencies, Google.ProtocolBuffers.Descriptors.Inte
    I/Unity   ( 4084): ArgumentOutOfRangeException: Argument is out of range.
    I/Unity   ( 4084): Parameter name: options
    I/Unity   ( 4084):   at System.Text.RegularExpressions.Regex.validate_options (RegexOptions options) [0x00000] in <filename unknown>:0
    I/Unity   ( 4084):   at System.Text.RegularExpressions.Regex..ctor (System.String pattern, RegexOptions options) [0x00000] in <filename unknown>:0
    I/Unity   ( 4084):   at Google.ProtocolBuffers.Descriptors.DescriptorPool..cctor () [0x00000] in <filename unknown>:0
    I/Unity   ( 4084): Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Google.ProtocolBuffers.Descriptors.DescriptorPool

    I/Unity   ( 4084):   at Google.ProtocolBuffers.Descriptors.FileDescriptor.BuildFrom (Google.ProtocolBuffers.DescriptorProtos.FileDescriptorProto proto, Google.ProtocolBuffers.Descriptors.FileDescriptor[] dependencies) [0x00000] in <filename unknown>:0
    I/Unity   ( 4084):   at Google.ProtocolBuffers.Descriptors.FileDescriptor.InternalBuildGeneratedFileFrom (System.Byte[] descriptorData, Google.ProtocolBuffers.Descriptors.FileDescriptor[] dependencies, Google.ProtocolBuffers.Descriptors.Inte

**Comment by milkshakeiii** [comment]
Thank you very much for this issue submission.  My first thought is the API compatibility level in player settings might need to be set to .NET 2.0, not .NET 2.0 subset.  I will take a closer look Monday.

**Comment by geekoftheweek** [comment]
That sounds very likely. I'll take a look tomorrow morning as well, but I
think you're probably right.

**Comment by milkshakeiii** [comment]
Another note about this, the requirement to use .NET 2.0 not .NET 2.0 subset is (I believe) gone in the most recent version of the plugin (release 1.2).  So an alternative solution could be to check out that branch!

**Comment by geekoftheweek** [comment]
You're right, changing the API compatibility level in the player settings resolved my problem.  Thank you!
